[profile.default]
src = "src"
test = "test"
out = "out"
libs = ["lib"]
solc_version = "0.8.30"
evm_version = "paris"
optimizer = true
optimizer_runs = 200
chain_id = 31337
remappings = ["forge-std/=lib/forge-std/src/"]

[profile.default.fuzz]
runs = 256
